name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository including .railway folder
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensure the full history for linked project

      # 2️⃣ Setup Node for Railway CLI
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # 4️⃣ Deploy service
      - name: Deploy via Railway
        working-directory: palstory-web
        run: |
          echo "Deploying service..."
          railway up --detach

      # 5️⃣ Print deployed service URL
      - name: Print service URL
        working-directory: palstory-web
        run: |
          echo "Deployed service URL:"
          railway run echo $RAILWAY_URL
