name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # 4️⃣ Authenticate CLI using project token
      - name: Authenticate Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "$RAILWAY_TOKEN" | railway login --token

      # 5️⃣ Deploy your service
      - name: Deploy service
        working-directory: palstory-web
        env:
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
        run: |
          echo "Deploying service $RAILWAY_SERVICE_NAME..."
          railway up --service "$RAILWAY_SERVICE_NAME" --detach

      # 6️⃣ Print deployed service URL
      - name: Print service URL
        working-directory: palstory-web
        env:
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
        run: |
          echo "Service URL:"
          railway run --service "$RAILWAY_SERVICE_NAME" echo $RAILWAY_URL
