name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Verify auth
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway whoami

      - name: Deploy via Railway (build from palstory-web/Dockerfile)
        working-directory: palstory-web
        env:
          RAILWAY_TOKEN:  ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT }}
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}
        run: |
          railway up \
            --project "$RAILWAY_PROJECT" \
            --service "$RAILWAY_SERVICE" \
            --detach